### ISSUE TITLE
Extremely slow with 10K customers

### ISSUE THREAD

**Issue by fatihalp** [akaunting/akaunting#1493]
### Steps to reproduce the issue

1. I've imported 10.000 customers.
2. Creating Invoice, Revenues etc. for all modules Can't select customer from list it's extremly slow. 
3. Also typing any other input is very slow.

### Actual result
 ![image](https://user-images.githubusercontent.com/219454/85142480-21f4ae00-b251-11ea-855d-76d3af093711.png)

### System information (Akaunting, PHP versions)
https://app.akaunting.com
Version 2.0.15

**Comment by hmert** [comment]
@fatihalp I've hardly recommend PostgreSQL for the database. You should consider Replication, Clustering and Connection Pooling [#](https://wiki.postgresql.org/wiki/Replication,_Clustering,_and_Connection_Pooling). 

On @monocash we have ~30k entries x 50k companies for testing purposes on top of K8S. It's performance is fair. We're looking for a more stable version to switch production.

I'll add also [php-pm](https://github.com/php-pm/php-pm) and Caddy web server to @akaunting/docker because of performance is not enough.

Let me know if you have any question.

**Comment by denisdulici** [comment]
It's not related either to DB or PHP but Vuejs as it's trying to show all customers in the select box at once, instead of doing search/autocomplete.

**Comment by fatihalp** [comment]
@denisdulici we want use on cloud but not possible to use with even 10.000 customers. Will it fixed short term? I see that there's remote option but in that case create new customer modal dissapears.

**Comment by denisdulici** [comment]
For sure that it'll be fixed but can't give any ETA.

**Comment by bd8392** [comment]
I just stumbled upon your software and this issue...By the way the software is amazing! I haven't tried it yet, but it is the only accounting-software I knot that is truly free...thanks for that amazing work! =) Im planing to use this in production and wonder, how scalable this is...are there more testers with 10.000+ customers? Is this working with mariadb? cause we're using mariadb =)

**Comment by asafov** [comment]
@fatihalp If app speed degrades at database side you can try Percona MySQL 5.7 version.
It have many good patches for DB work speed, try to run mysql-tuner at server and tune some variables.

**Comment by fatihalp** [comment]
@asafov 10 K is nothing for database. Speeding up database could be make faster page load. But page is not usable. The problem is in application side.

**Comment by asafov** [comment]
Sorry, missed message about vue miss to use autocomplete.
But Percona is real cool fork.

**Comment by cherryland** [comment]
akkounting is a monolithic application, it's only natural that it is **very slow**

**Comment by cuneytsenturk** [comment]
This issue sovled #1662

**Comment by asxcom** [comment]
Hello. How did you solve this problem? Could you share with us? I also go through this problem and it is almost impossible to use the system. It is clear that the problem is not with the hosting server I have, as other applications of similar complexity work without problems. Can anyone help to increase the performance? "xdebug" is disabled and so is the debug configuration (APP_DEBUG and DEBUGBAR_ENABLED)
