### ISSUE TITLE
Currency calculation in invoice doesn't work

### ISSUE THREAD

**Issue by lesdir** [akaunting/akaunting#1804]
The calculation of the product price in invoices doesn't work like it should. There is absolute no change in product price or total invoice amount. Only the currency symbol changes.

### Steps to reproduce the issue
Add MUR as additional currency
Let USD as second currency
Delete others currency

switch in company settings to MUR as default currency
Change cash account to MUR

In currencies:
MUR to 1
Set USD to 0.25 (exchange rate)

Add customers: 
Customer 1 default currency USD 
Customer 2 default currency MUR

Add item:
Test product - Sales Price 100MUR (If the company default currency is MUR, price is in MUR, I assume)

### Expected result
Test1:
Add new invoice and add customer 1 (default currency USD)
The currency symbol changes to USD
Add product 
Product price should be calculated from default sales price in MUR to USD (25USD) 
Total invoice amount etc should reflect the USD price (25 USD + tax)

Test2:
Add new invoice and add customer 2 (default currency MUR)
Currency symbol is MUR (which is correct)
Add product (price 100MUR)
Total price (100MUR plus Tax)
Now switch to USD for this invoice
All product prices should be calculated to USD and total amount of invioce too.

### Actual result
Test 1:
If I add a new product to the invoice the product price stays the same. No calculation happens. It should calculate the default price set in MUR to USD (default currency of customer)
The total invoice amount isn't calculated to USD (Only currency symbol changed)

Test2:
The currency symbol changes, but not the overall price of products or total amount. The amount is the same doesn't matter in which currency
The system shows (Currency conversion: 464.00 (MUR) at 0.25) which is right if I set the MUR sales price 1:1 to USD sales price, but this isn't a currency calculation only the change of the currency symbol.

### System information (Akaunting, PHP versions)
I used my own installation version 2.0.26, php7.4 and tried php7.3 same result
I also tried the cloud version offered from Akaunting.com, version 2.1.0, same result

### Additional comments
My own test installation runs on shared Interserver webhosting.

**Comment by halimturkoglu** [comment]
Hello,

This actually is the expected result since the currencies can be instantly changeable. I've added a sample screenshot of the "New Invoice" page that how it showed the currency rate when you add an item for a customer who has a different currency than your default one. It's like a suggestion on the page and it needs to be entered by you.

You can read the documentation here:

akaunting.com/docs

You can visit the Akaunting forum for such issues:

akaunting.com/forum

![currency](https://user-images.githubusercontent.com/49878455/105962598-1859e100-6091-11eb-92a2-e21ef7304c52.jpg)

This is not a bug. However, we appreciate your interest on Akaunting.

Regards,
