### ISSUE TITLE
Bill attachment not working

### ISSUE THREAD

**Issue by tarikcayir** [akaunting/akaunting#231]
![screenshot_1](https://user-images.githubusercontent.com/1753036/36645700-eb8c5bd2-1a7d-11e8-8682-b028dc7f9ca9.png)
![screenshot_2](https://user-images.githubusercontent.com/1753036/36645701-ebafbb86-1a7d-11e8-9083-27dd4875ef60.png)

**Comment by sebadamus** [comment]
Do you mean Company Logo not shown? because I see two different images, cant figure out...

I tested adding a bill, having a company logo uploaded and a bill attachment uploaded (in online Akaunting.com site) seems to work for me..

![captura1](https://user-images.githubusercontent.com/1787753/36772388-d7ff957c-1c33-11e8-9a5f-d75fa5832a05.PNG)
![captura2](https://user-images.githubusercontent.com/1787753/36772391-db093552-1c33-11e8-825a-cfa254842d10.PNG)
