### ISSUE TITLE
[2.1.33] Unable to delete Item

### ISSUE THREAD

**Issue by sshcli** [akaunting/akaunting#2366]
### Akaunting version

2.1.33

### PHP version

8.0.16

### Operating system

CentOS v7.9.2009 kvm

### Steps to reproduce

1. Install Akaunting in your own server
2. Try to delete an existing Item

### Expected result

You should be able to delete the Item without any problem

### Actual result

You get an error in console and the item is not deleted:

**Comment by rihards-simanovics** [comment]
Can you post the error here? If I understood correctly, you are trying to remove an item, but are you sure it is not related to any bills or invoices?
![image](https://user-images.githubusercontent.com/52106095/157484832-ca49f0c2-0f9f-43a6-9418-28ef627e9526.png)

**Comment by sshcli** [comment]
No. the item is not related to any invoice or bill.

Here is the error in console:

`items.js?v=2.1.33:1          DELETE https://example.com/1/common/items/9 403
(anonymous) @ items.js?v=2.1.33:1
e.exports @ items.js?v=2.1.33:1
e.exports @ items.js?v=2.1.33:1
Promise.then (async)
c.request @ items.js?v=2.1.33:1
(anonymous) @ items.js?v=2.1.33:1
(anonymous) @ items.js?v=2.1.33:1
c @ items.js?v=2.1.33:84
(anonymous) @ items.js?v=2.1.33:84
(anonymous) @ items.js?v=2.1.33:84
asyncGeneratorStep @ items.js?v=2.1.33:1
a @ items.js?v=2.1.33:1
(anonymous) @ items.js?v=2.1.33:1
(anonymous) @ items.js?v=2.1.33:1
(anonymous) @ items.js?v=2.1.33:1
Ke @ items.js?v=2.1.33:96
n @ items.js?v=2.1.33:96
Ke @ items.js?v=2.1.33:96
e.$emit @ items.js?v=2.1.33:96
onConfirm @ items.js?v=2.1.33:84
Ke @ items.js?v=2.1.33:96
n @ items.js?v=2.1.33:96
o._wrapper @ items.js?v=2.1.33:96
items.js?v=2.1.33:1 Error: Request failed with status code 403
    at e.exports (items.js?v=2.1.33:1:17582)
    at e.exports (items.js?v=2.1.33:1:20020)
    at XMLHttpRequest.y (items.js?v=2.1.33:1:12882)`

**Comment by rihards-simanovics** [comment]
Is this a fresh install and if so can you check permissions? You got 403 forbidden.

**Comment by sshcli** [comment]
The Delete button stay loading in loop, then the error shows in console, and nothing happens. The item is not deleted

**Comment by rihards-simanovics** [comment]
Ok, I don't want to generate a lot of noise here, as everyone will get notified each time one of us posts something here.
Let's take this chat offline and post the solution once we go through the basics. 

Email here qcixajy866@tormails.com (it's a temp email). I will reply from my actual email (I don't want to get spammed on my real one if anyone finds this thread).

**Comment by rihards-simanovics** [comment]
or alternatively we can chat here: https://temp.chat
just enter your name and the chatroom name `akountinghelp`

**Comment by rihards-simanovics** [comment]
Ok, I deleted the last two comments as I had no response. So I would first try and check my Nginx (or apache) logs if I were you. If nothing turns out there, I will move to PHP logs to see if there are any issues there.

If that doesn't show where the problem is, I would then move on to see if there are any issues with `file permissions` and `files ownership` to make sure everything inside the website root dir is accessible by the user executing the script.

If that is ok, I will move to the files themselves (in your case `items.js`), meaning I would try and recompile the JS, CSS, and others using npm script (try `npm run dev` first and if that works, I would then run `npm run prod` (make sure npm is installed beforehand)).

If I get any errors with running npm, I would then debug the npm issue, which can be any number of things beginning with a simple (i.e. date npm installation) and then moving to a more severe (i.e. package dependency issue).

So here is a checklist for you:
- [ ] - Nginx/Apache Logs (update issue description with the logs there)
- [ ] - PHP Error Logs (update issue description with the logs there)
- [ ] - Check File Permission
    - [ ] - Check Files Ownership
- [ ] - Recompile JS and CSS files
    - [ ] - If fails check npm version (try installing latest LTS version)
- [ ]  - if all the above fails try afresh [follow these steps precicly](https://github.com/akaunting/akaunting#installation)

I hope this helps. This is more or less the mental checklist I use before I submit the issue.
