### ISSUE TITLE
Item currency defaults back to the main currency

### ISSUE THREAD

**Issue by IbrahimS2** [akaunting/akaunting#2375]
### Akaunting version

2.1.33

### PHP version

7.4.21

### Operating system

Debian 11

### Steps to reproduce

- Create an invoice with secondary currency i.e USD
- items values in the secondary currency i.e USD
- Item one is 150 USD
- item two is 350 USD
- Save and mark the invoice as paid 

### Expected result

When navigating to items the value of the sales per item should be converted to the primary currency i.e USD to GBP for example considering the GBP is the primary currency so
item one is 150 USD => 115.03 GBP
item two is 350 USD => 268.40

### Actual result

It is displaying the same value in GBP/Primary currency which is wrong

### Additional comments

N/A

### Relevant log output

```shell
N/A
```

**Comment by cuneytsenturk** [comment]
If you use the `mark paid` button. it will add a default bank account and The bank account has currency.
You can read [documentation](https://akaunting.com/docs).

**Comment by IbrahimS2** [comment]
@cuneytsenturk This is irrelevant to what I am talking about; I am telling you the item sales lifetime is a miscalculation of the value if you are running multiple currencies.

**Comment by rihards-simanovics** [comment]
Hi @IbrahimS2, correcting the currency conversion (per Bill/invoice) is possible.

You need to check how much you paid in GBP and then fill the appropriate field on the invoice/bill:
![image](https://user-images.githubusercontent.com/52106095/160608758-8d28a777-13e9-466c-b6f7-bdf08dd1c88b.png)

I hope this helps!

**Comment by rihards-simanovics** [comment]
Word in advance, though.
There is a bug where once you make a bill/invoice in foreign currency, when you go to "Add Payment" (backdate it instead of marking it as paid on the day), the input field unintuitively require that you enter the GBP (or your main currency) instead of the currency displayed in the field in my case USD.
![image](https://user-images.githubusercontent.com/52106095/160610625-245b00ae-91da-4dda-ae73-4276e5735ae1.png)
