### ISSUE TITLE
Left menu not displaying on a fresh install

### ISSUE THREAD

**Issue by truekasun** [akaunting/akaunting#2648]
### Akaunting version

3.06

### PHP version

8.1

### Operating system

Ubuntu 20.04 (ARM64)

### Steps to reproduce

I have installed Akaunting as a fresh installation. Upon login, I get the following screen.

![image](https://user-images.githubusercontent.com/278469/193575727-14d3564b-9816-41fc-9013-41cb4e298f31.png)

I have tried clearing the cache, removing everything, and tried another fresh installation, but still the same result.

### Expected result

The left menu should be displayed

### Actual result

Left menu isn't displayingThe left

**Comment by atiabjobayer** [comment]
Same issue!

**Comment by raflymln** [comment]
Same issue here, even v3.0.9

**Comment by raflymln** [comment]
Hi guys, i've found the solution for this issue, recently i have already testing and checking everything, so what i found is that this problem can occur because of a few things:

1. Laravel does not have permission to storage and bootstrap cache directory
2. You have activated Cloudflare Rocket Loader to the website

So in order to fix this is easy

1. **Try add a permission to storage and bootstrap cache directory**
    a. Go to the installation directory, example:
    ```
    cd /var/www/akaunting
    ```
    
    b. Set the correct permissions on the cache and storage directories
    ```
    chmod -R 755 storage/* bootstrap/cache
    ```
    
    c. Try clearing the cache
    ```
    php artisan view:clear
    php artisan config:clear
    ```
    
    d. Don't forget to set the www- permission to the folder
    ```
    chown -R www-data:www-data /var/www/akaunting/*
    ```
    
2. **If solution above does not solve your issue, and if you're using Cloudflare to your site**
    a. Access your domain in the Cloudflare
    b. On the left sidebar, click **Speed**
    c. Click **Optimization**
    d. Search for **Rocket Loader** and turn it **off**

Also if you wanted the Rocket Loader off for akaunting site only, you could use **Page Rules** under **Rules** on your sidebar in Cloudflare.

However if the solution above doesn't work, you should be checking again your installation, make sure every php extensions required is available on your server, but if everything check and still nothing change, well, good luck finding the solution ✊

**Comment by atiabjobayer** [comment]
@raflymln  saved me. thanks a lotttt

**Comment by Androggles** [comment]
@raflymln For me it was the Rocket Loader. Thank you!
