### ISSUE TITLE
Error Add Primary Key Query 

### ISSUE THREAD

**Issue by andre-arc** [akaunting/akaunting#3116]
### Akaunting version

3.1.5

### PHP version

8.1.11

### Operating system

windows 11

### Steps to reproduce

- Install [Composer](https://getcomposer.org/download) and [Npm](https://nodejs.org/en/download)
- Clone the repository: git clone https://github.com/akaunting/akaunting.git
- Install dependencies: composer install ; npm install ; npm run dev
- php artisan install --db-name="akaunting" --db-username="root" --db-password="pass" --admin-email="admin@company.com" --admin-password="123456"

### Expected result

User account created

### Actual result

there is error query

<img width="910" alt="image" src="https://github.com/akaunting/akaunting/assets/11828823/6c53415e-5bf7-4b85-8fa6-65e4737eb15d">

**Comment by widada** [comment]
Same here, I've tried to change the original migration and still error

**Comment by mah3uz** [comment]
I have got this same error.
I checked and found that initially the `user_roles` table created with 3 columns `user_id, user_role & user_type` with primary index in `database/migrations/2017_09_14_000000_core_v1.php` 

And in `database/migrations/2022_07_21_000000_core_v305.php` its dropping primary index for `user_id, user_role & user_type` then adding primary index for `user_id, user_role` and last dropping the column `user_type`

So I assume that the purpose of this `2022_07_21_000000_core_v305.php` migration is dropping the `user_type` column.
Instead of dropping primary index for all three column primary index I just drop only `user_type` index then drop the `user_type` column.

And it worked. I don't know any underlying consequences 😀

This is the code:
```php
    public function up()
    {
        Schema::table('user_roles', function (Blueprint $table) {
            $table->dropPrimary(['user_type']);
//            $table->dropPrimary(['user_id', 'role_id', 'user_type']);
//            $table->primary(['user_id', 'role_id']);
        });

        Schema::table('user_roles', function (Blueprint $table) {
            $table->dropColumn('user_type');
        });
    }
```

**Comment by cuneytsenturk** [comment]
This issue solved this [commit](https://github.com/akaunting/akaunting/commit/c092c153761a5990090b70a11769e35179f0fbfc)
