### ISSUE TITLE
Error when export invoices

### ISSUE THREAD

**Issue by diegotmsousa** [akaunting/akaunting#3147]
### Akaunting version

3.1.6

### PHP version

8.1.17

### Operating system

Ubuntu 20.04

### Steps to reproduce

1 - Access my purchases > invoices

2 - Click on export results

### Expected result

Download the file with the listed records

### Actual result

Displays an error message with the following content:
- Error Class "MyCLabs\Enum\Enum"

### Relevant log output

```shell
When accessing the purchase or sales menu and trying to export the records, an error is displayed: MyCLabs\Enum\Enum

In previous versions it worked correctly, but this app was installed by a one-click install using digital ocean.

We are subscribing to the on-premise version and even so we have no support from the panel where tickets are being closed without a solution.
```

**Comment by cuneytsenturk** [comment]
Hello,

This error is usually caused by dependencies in the vendor folder. If there are errors when updating or during composer install/update, the files could not be downloaded completely or the remaining files from the old version could not be deleted.

Please delete your vendor folder and make sure that you have dumped the vendor folder from the latest version of akaunting to your server.

Then clean the laravel cache and start using.
