### ISSUE TITLE
Disabling few permissions not working

### ISSUE THREAD

**Issue by sabharat** [akaunting/akaunting#322]
On Unchecking the "Read Admin Panel" and "Read Settings Currencies" for a role in version 1.1.15 , the user with that role  is not able to login.

**Steps to reproduce the issue**
Go to Roles list and edit to see the permissions associated with the role.
Uncheck either of "Read Admin Panel" or "Read Settings Currencies" permissions.
**Expected result**
Admin panel or correncies read shoul not show up

**Actual result**
The user with that role is not able to  login or continue the current session

**System information (Akaunting, PHP versions)**
Akaunting version 1.1.15
Php version 7.0

**Comment by denisdulici** [comment]
I just tested this and was able to login after unchecking the "Read Settings Currencies". If you uncheck the "Read Admin Panel" permision then you **must** check "Read Customer Panel" otherwise it's more than normal to not login.

Akaunting has 2 panels, admin and customer, so you must give permission to read at least one of them.
