### ISSUE TITLE
Invoice add payment problem

### ISSUE THREAD

**Issue by batuhawk** [akaunting/akaunting#412]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
Problem about invoices.
When I added payment on the bill,  digits after the decimal point(total) are rounded automatically and
in the invoice table, the total amount and paid is changing, after adding payment.

### Expected result
322,95 expected 322,95

### Actual result
For example :  322,95 rounded 322,00

### System information (Akaunting, PHP versions)
Akaunting Version 1.2.10
PHP 7.1

**Comment by ramonleenders** [comment]
This doesn't seem to be fixed. When I've got an invoice with for example this amount:

245,03 

I can add it as 245,03 (I can not do 245.03, which I thought I always did before though, because that will make it 24503 instead). After adding, it is perfectly added as amount 245.03 in the database column (invoice_payments), but the invoice_histories table says 245,00 payment... So the amounts are being treated differently throughout the system.

My precision with my enabled default currency is 2, and in Euros. The decimal mark is set to , and the thousands to .

**Comment by ramonleenders** [comment]
To make it work, I had to add (float) to the amount variable here:

_app/Http/Controllers/Incomes/Invoices.php:772_

So that makes:

`(float) $request['amount']`

It's casted as a float a bit downward in the file too, so seemed the most obvious. Of course, you can cast it earlier too, so you don't need to do it twice? I'm adding payments with dots again, so 245.03 as the example above (so **no comma** -> 245,03).
