### ISSUE TITLE
Slow response when adding item for an invoice

### ISSUE THREAD

**Issue by Feltim** [akaunting/akaunting#530]
### Steps to reproduce the issue
Clean installation on local machine.
Run setup.
Click on add invoice.
Click on add item (blue plus sign)

### Expected result
Less than 0.1 second response time for client side JS to generate line item. 
Similar to deleting line item in speed.

### Actual result
Longer than 4.6 seconds response time to add an item to an invoice, sometimes over 10 seconds.

### System information (Akaunting, PHP versions)
Akaunting: Version 1.2.16
PHP: Version 5.6.25

### Additional comments
Creating invoices of 30 items will take over 2 mins just waiting for line items to open up. Cannot reasonably expect accountant to work with the software.

![slow invoice](https://user-images.githubusercontent.com/43956302/46607888-ee1c3800-cb02-11e8-9702-add48df58816.png)

**Comment by denisdulici** [comment]
I'm not able to reproduce such an issue but I would advise to check it with your hosting provider. Feel free to use the forum for further help.

**Comment by asxcom** [comment]
Hello. How did you solve this problem? Could you share with us? I also go through this problem and it is almost impossible to use the system. It is clear that the problem is not with the hosting server I have, as other applications of similar complexity work without problems. Can anyone help to increase the performance? "xdebug" is disabled and so is the debug configuration (APP_DEBUG and DEBUGBAR_ENABLED)
