### ISSUE TITLE
The currency Vietnamese Dong doesn't seem to work

### ISSUE THREAD

**Issue by maximstevens** [akaunting/akaunting#531]
Please, submit only real issues. Use the forum for support, feature requests, proposals, new versions, help etc. https://akaunting.com/forum

### Steps to reproduce the issue
I need to value each item per gram. In this case it would be VND55 for sale and VND35 for purchasing. 

### Expected result
When selling 1kg this should automatically change to VND55,000.

### Actual result
The software only logs the price at VND55 but then does not allow any amendments on the invoice and does not give a invoice total.

### System information (Akaunting, PHP versions)
Akounting

**Comment by denisdulici** [comment]
Sorry for the late reply. I was not able to reproduce such an issue but you can use the forum if you need further support.

**Comment by hirako2000** [comment]
Why is this closed? It's a bug.

The VND currency is barely usable. Steps to reproduce:

- Create a new expense (Bill)
- Add an item, with unit price of 150000, quantity 3
- Add another item via clicking on the icon, set unit price to 200000, quantity 2.
- Click save.
- Then access this Saved bill, and edit, try to edit any of the two item's unit price, and focus out of the amount, see the total and unit price gets their value changed!

The only work around is to type enter with the keyboard, instead of click save. and that without focusing out of any of the unit price field. It makes it very difficult to fill and even more complicated to edit bills.
