### ISSUE TITLE
Can`t finish the 3rd installation step when setting the app with Docker. 

### ISSUE THREAD

**Issue by naneri** [akaunting/akaunting#532]
I have tried to install the software in a local container, but I cant go past the 3rd step. It says `SQLSTATE[HY000] [2002] Connection refused (SQL: insert into `ak_companies` (`domain`, `updated_at`, `created_at`) values (, 2018-10-09 06:56:02, 2018-10-09 06:56:02))`, but it did pass the database setup step correctly, so I am really lost and cant get why it complains. 

### Steps to reproduce the issue
Install the app via docker. Go to the app URL and start the installation. Go through the installation steps and on step 3 fill all the company info and save.

### Expected result
It should install correctly. 

### Actual result
It fails with error `SQLSTATE[HY000] [2002] Connection refused (SQL: insert into `ak_companies` (`domain`, `updated_at`, `created_at`) values (, 2018-10-09 06:56:02, 2018-10-09 06:56:02))`

### System information (Akaunting, PHP versions)
docker

### Additional comments
![screenshot from 2018-10-09 12-58-33](https://user-images.githubusercontent.com/5573469/46651890-4a469100-cbc3-11e8-8823-baf61b9b6039.png)

**Comment by birkof** [comment]
@naneri I installed everything from master branch and it worked without any problem.
On a first look at your error seems like you are missing some inputs, like domain. 
Check your console for any errors, before.

**Comment by naneri** [comment]
@birkof I have accessing the project via url - 127.0.0.1:8080 
In the log it says `AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.24.0.3. Set the 'ServerName' directive globally to suppress this message`

Concerning the inputs - there is no input such as `domain`. In the first 3 steps, there is only language, database settings and company details.

**Comment by naneri** [comment]
@birkof any comments?

**Comment by jhughes2112** [comment]
I have the same problem, after fighting to get it to work in Docker for three days.  Finally, sorting out the other issues, it fails on the third step.  :-(  The database has the following tables in it:

`mysql> show tables;
+------------------------+
| Tables_in_db_akaunting |
+------------------------+
| bap_accounts           |
| bap_bill_histories     |
| bap_bill_item_taxes    |
| bap_bill_items         |
| bap_bill_payments      |
| bap_bill_statuses      |
| bap_bill_totals        |
| bap_bills              |
| bap_categories         |
| bap_companies          |
| bap_currencies         |
| bap_customers          |
| bap_failed_jobs        |
| bap_invoice_histories  |
| bap_invoice_item_taxes |
| bap_invoice_items      |
| bap_invoice_payments   |
| bap_invoice_statuses   |
| bap_invoice_totals     |
| bap_invoices           |
| bap_items              |
| bap_jobs               |
| bap_media              |
| bap_mediables          |
| bap_migrations         |
| bap_module_histories   |
| bap_modules            |
| bap_notifications      |
| bap_password_resets    |
| bap_payments           |
| bap_permissions        |
| bap_reconciliations    |
| bap_recurring          |
| bap_revenues           |
| bap_role_permissions   |
| bap_roles              |
| bap_sessions           |
| bap_settings           |
| bap_taxes              |
| bap_transfers          |
| bap_user_companies     |
| bap_user_permissions   |
| bap_user_roles         |
| bap_users              |
| bap_vendors            |
+------------------------+
45 rows in set (0.00 sec)
`

The error is this:
`

(3/3) QueryExceptionSQLSTATE[HY000] [2002] Connection refused (SQL: insert into `ak_companies` (`domain`, `updated_at`, `created_at`) values (, 2019-02-10 15:39:42, 2019-02-10 15:39:42))
--
in Connection.php line 647
at Connection->runQueryCallback('insert into `ak_companies` (`domain`, `updated_at`, `created_at`) values (?, ?, ?)', array('', '2019-02-10 15:39:42', '2019-02-10 15:39:42'), object(Closure))in Connection.php line 607

`

**Comment by jhughes2112** [comment]
Here's the docker-compose.yaml that I use to bring up the service.  The directory structure I used, if you want it to be exactly reproducible, is like so:
/opt/ak/docker-compose.yaml
/opt/ak/mysql/varlibmysql/
/opt/ak/akaunting/varwwwhtml/    <-- git clone to here
/opt/ak/akaunting/etcapache2/

This is running as a user, with the volumes mounted with my user permissions (1000:1000) so I don't want the file permissions to be set to www-data. Thus the strange way I have to launch Apache.  But it works ok, up until the 3rd step of the install.  If you look in the mysql/varlib/db_akaunting folder, there will be files starting with bap_ instead of ak_, which is also an indication the tables are prefixed incorrectly when created.

Little help?

`version: '3'
services:
  mysql:
    image: mysql:5
    container_name: akaunting_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: somerootpw
      MYSQL_DATABASE: db_akaunting
      MYSQL_USER: akaunting
      MYSQL_PASSWORD: akauntingpw
    volumes:
      - ./mysql/varlibmysql:/var/lib/mysql
  akaunting:
    image: akaunting
    command: [ "bash", "-c", "groupadd localuser -g 1000; useradd -u 1000 -g 1000 localuser; export APACHE_RUN_USER=localuser; export APACHE_RUN_GROUP=localuser; composer install; apache2-foreground" ]
    container_name: akaunting_akaunting
    restart: unless-stopped
    volumes:
      - ./akaunting/varwwwhtml:/var/www/html
      - ./akaunting/etcapache2:/etc/apache2
    ports:
      - "82:80"
    environment:
      APP_DEBUG: "true"
    links:
      - mysql:mysql
`

**Comment by jhughes2112** [comment]
@birkof Any help please?  I gave pretty solid details on the problem and it's quite reproducible.  I'd like to use your software, if it would install for me.  Thanks!

**Comment by jhughes2112** [comment]
Ok, I hate that this took me so long to figure out, but given I have no idea about Akaunting, this was kind of a problem to uncover.  The issue is that nginx is configured to drop connections at 60 seconds, which is approximately when the 2nd step fails to generate the complete database.

Stop both mysql and the akaunting dockers.  Make sure you delete everything under the mysql folder so the DB has to regenerate.  This is important, otherwise it fails in step 2 again.  Also make sure you find the ".env" file and rename it to ".env.example" inside the akaunting folder, otherwise it won't install cleanly.

Basically, go into the nginx.conf file where http { block } is, and look for (or add) the following two lines:
        fastcgi_read_timeout 300;
        proxy_read_timeout 300;
        keepalive_timeout 300;

ALSO, inside the nginx/site-confs/default file, you will also find keepalive_timeout set to something low like 60.  Bump it up to 300 as well.

Restart both containers, and it should work fine.  This took me months to screw with and finally get running.  I use docker-compose that looks like this now:

`version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: akaunting_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=akaunting
      - MYSQL_USER=ak
      - MYSQL_PASSWORD=akpw
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql.cnf:/etc/mysql/conf.d/more.cnf

  akaunting:
    image: woahbase/alpine-akaunting:x86_64
    container_name: akaunting
    depends_on:
      - mysql
    volumes:
      - ./config:/config
      - ./php_connection_timeout.ini://etc/php7/conf.d/php_connection_timeout.ini
    ports:
      - 82:80
    environment:
      - PGID=1000
      - PUID=1000
    links:
      - mysql
`

**Comment by jhughes2112** [comment]
I would ALSO mention that the application will redirect to the wrong port if you are internally hosting on a port-80 server and have mapped it to anything other than port-80.  I found it easier to change the Nginx config file to serve it on 82 (config/nginx/site-configs/default), and map it pubicly as 82, which means I changed the docker-compose.yml to map "- 82:82" above.

I also edited config/www/akaunting.htaccess and commented out the following lines:
    # Redirect Trailing Slashes If Not A Folder...
#    RewriteCond %{REQUEST_FILENAME} !-d
#    RewriteRule ^(.*)/$ /$1 [L,R=301]

Then, remember to clear your browser history/cache otherwise any permanent redirects you have already hit by accident will keep happening even AFTER you stop/restart the docker containers, which is really infuriating.  Hope this helps anyone else out there struggling with this stuff!

**Comment by kocuubirasap** [comment]
me too, I get error 
![error login akaunting application](https://user-images.githubusercontent.com/47787361/59448080-a20e5980-8e2e-11e9-9b66-bb4467dd18d9.png)

**Comment by denisdulici** [comment]
Please, continue this on our Docker repo.
