### ISSUE TITLE
Add multiple tax rate to an invoice item

### ISSUE THREAD

**Issue by EAEvidence** [akaunting/akaunting#54]
It would be great to be able to put more than only one tax rate on an invoice item

**Comment by denisdulici** [comment]
I can see it for the whole invoice but not really for an invoice item. Any known system that applies it?

**Comment by drbyte** [comment]
Most tax strategies that incorporate multiple taxes per line item will do it by assigning a "tax class".
For example, "B" in the following list is a class that combines the rates of 2 other classes:
And then the arithmetic for calculating totals applies the respective taxes per line item, to arrive at the multiple subtotals for taxes. This also allows for reporting of how much of each tax was collected, in order to remit those amounts to the respective tax collection authorities.

Code = Description
- V = VAT
- G = GST
- P = PST
- B = Both GST+PST
- X = Tax-Exempt

**Comment by vkkan** [comment]
Yes @denisdulici @drbyte  its makes sense to have more than one taxes per line items , for ex some items will have GST bucket in different percentages in india as major slabs - 0%, 5%, 12%, 18% and 28% , goods and services taxed under various GST slabs

**Comment by denisdulici** [comment]
Guys, feature requests are welcomed to the Ideas section of our [forum](https://akaunting.com/forum).

I've also added this item to our poll https://akaunting.com/forum/discussion/announcements/poll-for-akaunting-12
