### ISSUE TITLE
Logo Link forwards to a page which omits port setting

### ISSUE THREAD

**Issue by hakanurhan** [akaunting/akaunting#839]
### Steps to reproduce the issue
I installed Akaunting behind an NGinx proxy and the proxy serves from port 9000. The proxy is based on a hostname rule "akaunting.mycompany". So I use http://akaunting.mycompany:9000/akaunting/ to access Akaunting web interface. Everything works smooth except the "Home" link (the logo on top left corner). When I hover the mouse over the logo image, I see http://akaunting.mycompany:9000/akaunting/ - which is OK. However when I click, I see that the port is removed and I end up with http://akaunting.mycompany/akaunting/ which gives me a 404 page. I couldn't find anywhere in the config files or sources to change this hostname/port.

### Expected result
When logo is clicked the should take me to http://akaunting.mycompany:9000/akaunting/

### Actual result
I takes me to http://akaunting.mycompany/akaunting/ (port missing)

### System information (Akaunting, PHP versions)
Akauntin 1.3.17
PHP7

**Comment by themazim** [comment]
Seems like a redirect issue, can you provide the redirects? Chrome extension "Redirect Path" could be very helpful in this case.

**Comment by hakanurhan** [comment]
I couldn't make use of the redirect path extension because it lost all the traces when the redirect was 404.
Instead I used Chrome's Developer Tools (Network) to capture the requests/responses and headers just after the click to the logo. Please find the HAR file attached (renamed to .txt). It's just a JSON file with timestamps. It looks understandable to me, and I'm sure you can make something out of it (well, I hope).

[chromewebdata.txt](https://github.com/akaunting/akaunting/files/3283148/chromewebdata.txt)

**Comment by themazim** [comment]
So, afaik, this is what's happening:

```
http://akaunting.ardiclabs:9000/akaunting/ (starting page)
Click on the logo, links to: http://akaunting.ardiclabs:9000/akaunting
Response with redirect (301) to http://akaunting.ardiclabs/akaunting/ 
```
after the redirect chrome tries some stuff to get a valid server / response, which fails.

I guess the issue is with the URL build for the logo and the missing "/" at the end of it.

When you open http://akaunting.ardiclabs:9000/akaunting/ in another tab, everything is working fine, right?

What's in your .env for APP_URL?

**Comment by hakanurhan** [comment]
thanks @themazim . It's indeed the problem. I tried entering the URLs http://akaunting.ardiclabs:9000/akaunting/ and http://akaunting.ardiclabs:9000/akaunting. The URL ending with "/" works just fine, where the one without it gives indeed 404 page.

I checked the ".env" file (I haven't touched it manually, I used the wizard. So all the values were either default or set by wizard) for the `APP_URL` setting. There was no such setting. So I added the following line but it made no difference. What shall I set it to?

`APP_URL="https://akaunting.ardiclabs:9000/akaunting/"`

**Comment by themazim** [comment]
Your App URL is fine, I just thought maybe something wrong with it. You can leave it blank.

The expected behaviour for `url('/')` is to create a link to https://www.your-domain.com (without) the / at the end, so this is just fine. 

I would guess your nginx setup and using a subfolder for akaunting is the problem. 
The URL `/akaunting` is not rewriting / passing the request correctly through to the subfolder (akaunting/index.php), instead tries to serve something else a index.php in the root folder (/index.php).

**Comment by hakanurhan** [comment]
Thanks to you, I now know the reason for this behaviour (the missing trailing /). Since I didn't think it was relevant I didn't mention that there'a a reverse proxy before Akaunting (nginx) server. (I use Traefik as Reverse Proxy). I'll focus on the configuration of both Akaunting Nginx and Traefik. I strongly believe this is the rev. proxy conf. problem. So I will close this issue and open another one in case I find any relevance directly to Akaunting.
Thanks for the tips.
