### ISSUE TITLE
Seeder

### ISSUE THREAD

**Issue by kocuubirasap** [akaunting/akaunting#841]
run command php artisan db:seed, but dummy data has not been inserted. Can anyone help this case ? thanks

**Comment by themazim** [comment]
any errors? What does the log say?

**Comment by kocuubirasap** [comment]
Where i can find error log? on my terminal no error log. But the class for seeder do nothing

**Comment by themazim** [comment]
Log location: storage/logs/laravel.log

The seeder should be called automatically and should seed you company, you can rerun the seeder for a specific company with:  

`php artisan company:seed <company_id>`

Working example if your company ID is 1:

`php artisan company:seed 1`

**php artisan db:seed** won't fill you database with any data, since its not configured.

**Comment by kocuubirasap** [comment]
Okay thanks @themazim , that works for me.
Oy, how to run TestCompany seed ?

**Comment by themazim** [comment]
**I do not recommend this**, since it's for testing purposes only and you will run into errors, but you can run a very basic company test seed with a default user (admin@akaunting.com / 123456) with:

`php artisan db:seed --class=\\Database\\Seeds\\TestCompany --force`

**Comment by kocuubirasap** [comment]
Ok thanks very much @themazim. Thats work for me.
