### ISSUE TITLE
Version 2.0.0 bugs

### ISSUE THREAD

**Issue by o2-web** [akaunting/akaunting#901]
1. Dropdown items in the left menu are not expanded
2. The updates section does not work correctly
3. Uploading the company logo does not work

### Steps to reproduce the issue
Fresh Install version 2.0.0

1. Try to expand dropdown items in the left menu
2. Go to the updates section http://crm.openvisor.ru/install/updates
3. Try to upload company logo on http://crm.openvisor.ru/common/companies/1/edit

### System information (Akaunting, PHP versions)
Akaunting version 2.0.0 (russian localization)
Linux, Nginx, PHP 7.3

### Additional comments
http://crm.openvisor.ru

Login: admin@example.org
Pass: crm8080

**Comment by denisdulici** [comment]
1) This is related to Russian translation, there is an extra space added before/after the pipeline:

![screenshot_1573993251](https://user-images.githubusercontent.com/5254835/69007357-df32c680-094d-11ea-935c-a71d752f20eb.jpg)

Can you please join the translation team and fix/finish the Russian translation? https://crowdin.com/project/akaunting

2) What is exactly wrong with the updates?

3) What happens when you upload the logo?

**Comment by o2-web** [comment]
1. I will try to complete the translations when I have free time
2. The updates page States that the current version is 2.0.0 and the latest version is 1.3.17, also:
    Offline Payments App - current version 2.0.0, and the lates version 1.0.0
    PayPal Standard App - current version 2.0.0, and the lates version 1.0.0
3. When I upload the company logo, nothing happens. This is probably due to javascript errors. Here is one of the errors from the browser console: 
`companies.js?v=2.0.0:74238 [Vue warn]: Property or method "email" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.`

**Comment by denisdulici** [comment]
This has been fixed in master.
